name = "ivanlawrence-com"
compatibility_date = "2024-05-08"

# This property is required by Wrangler for Cloudflare Pages.
# It specifies the directory of static assets to upload.
pages_build_output_dir = "public"

# The following configuration is optional but recommended for local development
# using `wrangler pages dev`. It tells Wrangler how to build your site.
[build]
command = "hugo"

# Environment variables for the build
[vars]
HUGO_VERSION = "0.124.1"
